"use client"
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/TdS2SAgk9nJ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { TimerIcon } from "lucide-react"
import { ClockIcon } from "lucide-react"
import { ListIcon } from "lucide-react"
import { UserIcon } from "lucide-react"
import { SettingsIcon } from "lucide-react"
export default function Home() {
  
  const handleCreateAccount = async() => {
    const response = await fetch('http://localhost:3002/create-keypair',{
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
    });
    const data = await response.json();
    console.log(data);
  }
  return (
    <div className="flex min-h-screen w-full">
    
      <div className="flex flex-col w-[35vh] border-r bg-[#0B0014] text-white ">
        <div className="flex h-[60px] text-2xl items-center border-b px-6">
          <Link href="#" className="flex items-center gap-2 font-semibold" prefetch={false}>
            <TimerIcon className="h-6 w-6 text-[#26A7F7]" />
            <span className="">TaskChain</span>
          </Link>
        </div>
        <div className="flex-1 overflow-auto py-2">
          <nav className="grid gap-1 px-4 text-xl font-medium">
          <div className="flex items-center gap-2 text-muted-foreground">
              <Button onClick={handleCreateAccount} className="bg-[#022D50] px-2 py-2 w-[14vw] h-[5vh] text-md hover:bg-[#17507e] text-white">Add Wallet</Button>
            </div>
            <Link
              href="#"
              className="flex items-center gap-5 rounded-lg px-3 py-3 text-primary transition-all hover:bg-[#022D50]"
              prefetch={false}
            >
              <UserIcon className="h-4 w-4" />
              Account
            </Link>
            <Link
              href="#"
              className="flex items-center gap-3 rounded-lg px-3 py-3 text-muted-foreground transition-all hover:bg-[#022D50]"
              prefetch={false}
            >
              <SettingsIcon className="h-4 w-4" />
              Settings
            </Link>
            
            <Link
              href="#"
              className="flex items-center gap-3 rounded-lg px-3 py-3 text-muted-foreground transition-all hover:bg-[#022D50]"
              prefetch={false}
            >
              <ClockIcon className="h-4 w-4" />
              History
            </Link>
            <Link
              href="#"
              className="flex items-center gap-3 rounded-lg px-3 py-3 text-muted-foreground transition-all hover:bg-[#022D50]"
              prefetch={false}
            >
              <ListIcon className="h-4 w-4" />
              Manage Tasks
            </Link>
          </nav>
        </div>
      </div>
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-12">
        
      <h1 className="text-3xl font-bold mb-8">Find the Perfect Task</h1>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8">
        <div className="bg-white rounded-lg shadow-md overflow-hidden hover:bg-gray-300">
          <div className="p-6">
            <h2 className="text-xl font-semibold mb-2">Web Development ($100)</h2>
            <p className="text-muted-foreground mb-4">Skilled web developers to build your online presence.</p>
            <Button className="w-full bg-[#2d8ddb] hover:bg-[#17507e] text-white">Start</Button>
          </div>
        </div>
        <div className="bg-white rounded-lg shadow-md overflow-hidden hover:bg-gray-300">
          <div className="p-6">
            <h2 className="text-xl font-semibold mb-2">Graphic Design ($20)</h2>
            <p className="text-muted-foreground mb-4">Talented designers to create stunning visuals.</p>
            <Button className="w-full bg-[#2d8ddb] hover:bg-[#17507e] text-white">Start</Button>
          </div>
        </div>
        <div className="bg-white rounded-lg shadow-md overflow-hidden hover:bg-gray-300">
          <div className="p-6">
            <h2 className="text-xl font-semibold mb-2">Digital Marketing ($70)</h2>
            <p className="text-muted-foreground mb-4">Experts to help you reach your target audience.</p>
            <Button className="w-full bg-[#2d8ddb] hover:bg-[#17507e] text-white">Start</Button>
          </div>
        </div>
        <div className="bg-white rounded-lg shadow-md overflow-hidden hover:bg-gray-300">
          <div className="p-6">
            <h2 className="text-xl font-semibold mb-2">Content Writing ($60)</h2>
            <p className="text-muted-foreground mb-4">Skilled writers to create compelling content.</p>
            <Button className="w-full bg-[#2d8ddb] hover:bg-[#17507e] text-white">Start</Button>
          </div>
        </div>
        <div className="bg-white rounded-lg shadow-md overflow-hidden hover:bg-gray-300">
          <div className="p-6">
            <h2 className="text-xl font-semibold mb-2">Mobile Development ($120)</h2>
            <p className="text-muted-foreground mb-4">Experienced mobile app developers.</p>
            <Button className="w-full bg-[#2d8ddb] hover:bg-[#17507e] text-white">Start</Button>
          </div>
        </div>
        <div className="bg-white rounded-lg shadow-md overflow-hidden hover:bg-gray-300">
          <div className="p-6">
            <h2 className="text-xl font-semibold mb-2">Data Analysis ($50)</h2>
            <p className="text-muted-foreground mb-4">Experts to help you make data-driven decisions.</p>
            <Button className="w-full bg-[#2d8ddb] hover:bg-[#17507e] text-white">Start</Button>
          </div>
        </div>
        <div className="bg-white rounded-lg shadow-md overflow-hidden hover:bg-gray-300">
          <div className="p-6">
            <h2 className="text-xl font-semibold mb-2">Virtual Assistant ($40)</h2>
            <p className="text-muted-foreground mb-4">Skilled assistants to help you stay organized.</p>
            <Button className="w-full bg-[#2d8ddb] hover:bg-[#17507e] text-white">Start</Button>
          </div>
        </div>
        <div className="bg-white rounded-lg shadow-md overflow-hidden hover:bg-gray-300">
          <div className="p-6">
            <h2 className="text-xl font-semibold mb-2">Accounting ($50)</h2>
            <p className="text-muted-foreground mb-4">Professionals to handle your financial needs.</p>
            <Button className="w-full bg-[#2d8ddb] hover:bg-[#17507e] text-white">Start</Button>
          </div>
        </div>
      </div>
    </div>
    </div>
  )
}
