/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/9ZEBpHQctq1
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Rubik } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { TooltipProvider, Tooltip, TooltipTrigger, TooltipContent } from "@/components/ui/tooltip"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Breadcrumb, BreadcrumbList, BreadcrumbItem, BreadcrumbLink, BreadcrumbSeparator, BreadcrumbPage } from "@/components/ui/breadcrumb"
import { Input } from "@/components/ui/input"
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { TimerIcon } from "lucide-react"
import { ClockIcon } from "lucide-react"
import { ListIcon } from "lucide-react"
import { Badge } from "@/components/ui/badge"

export default function Userdashboard() {
  return (
    <div className="flex min-h-screen w-full">
      <div className="flex flex-col border-r bg-background">
        <div className="flex h-[60px] items-center border-b px-6">
          <Link href="#" className="flex items-center gap-2 font-semibold" prefetch={false}>
            <TimerIcon className="h-6 w-6" />
            <span>Taskmaster</span>
          </Link>
        </div>
        <div className="flex-1 overflow-auto py-2">
          <nav className="grid gap-1 px-4 text-sm font-medium">
          <div className="relative">
              <Input
                type="search"
                placeholder="Search tasks..."
                className="w-full rounded-lg bg-muted px-8 py-2 text-sm"
              />
              <SearchIcon className="absolute left-2 top-2 h-4 w-4 text-muted-foreground" />
            </div>
            <Link
              href="#"
              className="flex items-center gap-3 rounded-lg px-3 py-2 text-primary transition-all hover:bg-muted"
              prefetch={false}
            >
              <UserIcon className="h-4 w-4" />
              Account
            </Link>
            <Link
              href="#"
              className="flex items-center gap-3 rounded-lg px-3 py-2 text-muted-foreground transition-all hover:bg-muted"
              prefetch={false}
            >
              <SettingsIcon className="h-4 w-4" />
              Settings
            </Link>
            <Link
              href="#"
              className="flex items-center gap-3 rounded-lg px-3 py-2 text-muted-foreground transition-all hover:bg-muted"
              prefetch={false}
            >
              <ClockIcon className="h-4 w-4" />
              History
            </Link>
            <Link
              href="#"
              className="flex items-center gap-3 rounded-lg px-3 py-2 text-muted-foreground transition-all hover:bg-muted"
              prefetch={false}
            >
              <ListIcon className="h-4 w-4" />
              Manage Tasks
            </Link>
          </nav>
        </div>
      </div>
      
      <div className="flex flex-1 flex-col sm:pl-14 md:pl-18 lg:pl-20">
        <header className="sticky top-0 z-30 flex h-14 items-center gap-4 border-b bg-background px-4 sm:static sm:h-auto sm:border-0 sm:bg-transparent sm:px-6 md:h-16 md:px-8 lg:h-20 lg:px-10">
          <Breadcrumb className="hidden md:flex">
            <BreadcrumbList>
              <BreadcrumbItem>
                <BreadcrumbLink asChild>
                  <Link href="#" prefetch={false}>
                    Dashboard
                  </Link>
                </BreadcrumbLink>
              </BreadcrumbItem>
              <BreadcrumbSeparator />
              <BreadcrumbItem>
                <BreadcrumbPage>Tasks</BreadcrumbPage>
              </BreadcrumbItem>
            </BreadcrumbList>
          </Breadcrumb>
          
        </header>
        <main className="grid flex-1 items-start gap-4 p-4 sm:px-6 sm:py-0 md:gap-8 md:p-8 lg:gap-10 lg:p-10">
          <div className="grid w-full grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            <Card>
              <CardHeader className="flex flex-row items-center justify-between pb-2">
                <CardTitle className="text-sm font-medium md:text-base lg:text-lg">Completed Tasks</CardTitle>
                <ClipboardIcon className="w-4 h-4 text-muted-foreground md:w-5 md:h-5 lg:w-6 lg:h-6" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold md:text-3xl lg:text-4xl">125</div>
                <Progress value={75} aria-label="75% completed" />
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="flex flex-row items-center justify-between pb-2">
                <CardTitle className="text-sm font-medium md:text-base lg:text-lg">In Progress</CardTitle>
                <ClipboardListIcon className="w-4 h-4 text-muted-foreground md:w-5 md:h-5 lg:w-6 lg:h-6" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold md:text-3xl lg:text-4xl">32</div>
                <Progress value={45} aria-label="45% in progress" />
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="flex flex-row items-center justify-between pb-2">
                <CardTitle className="text-sm font-medium md:text-base lg:text-lg">Upcoming</CardTitle>
                <CalendarIcon className="w-4 h-4 text-muted-foreground md:w-5 md:h-5 lg:w-6 lg:h-6" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold md:text-3xl lg:text-4xl">78</div>
                <Progress value={25} aria-label="25% upcoming" />
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="flex flex-row items-center justify-between pb-2">
                <CardTitle className="text-sm font-medium md:text-base lg:text-lg">Projected Revenue</CardTitle>
                <DollarSignIcon className="w-4 h-4 text-muted-foreground md:w-5 md:h-5 lg:w-6 lg:h-6" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold md:text-3xl lg:text-4xl">$45,231.89</div>
                <Progress value={80} aria-label="80% projected" />
              </CardContent>
            </Card>
          </div>
          <div>
            <Card>
              <CardHeader className="px-7 md:px-10 lg:px-12">
                <CardTitle className="text-base md:text-lg lg:text-xl">Recent Tasks</CardTitle>
                <CardDescription className="text-sm md:text-base lg:text-lg">
                  A summary of your most recent tasks.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead className="text-sm md:text-base lg:text-lg">Task</TableHead>
                      <TableHead className="hidden sm:table-cell text-sm md:text-base lg:text-lg">Status</TableHead>
                      <TableHead className="hidden sm:table-cell text-sm md:text-base lg:text-lg">Due Date</TableHead>
                      <TableHead className="text-right text-sm md:text-base lg:text-lg">Estimated Revenue</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell>
                        <div className="font-medium text-base md:text-lg lg:text-xl">Redesign homepage</div>
                        <div className="hidden text-sm text-muted-foreground sm:inline md:text-base lg:text-lg">
                          Update the homepage design
                        </div>
                      </TableCell>
                      <TableCell className="hidden sm:table-cell text-sm md:text-base lg:text-lg">
                        <Badge className="text-xs md:text-sm lg:text-base" variant="secondary">
                          In Progress
                        </Badge>
                      </TableCell>
                      <TableCell className="hidden sm:table-cell text-sm md:text-base lg:text-lg">2023-06-30</TableCell>
                      <TableCell className="text-right text-base md:text-lg lg:text-xl">$2,500.00</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>
                        <div className="font-medium text-base md:text-lg lg:text-xl">Implement new feature</div>
                        <div className="hidden text-sm text-muted-foreground sm:inline md:text-base lg:text-lg">
                          Add a new feature to the app
                        </div>
                      </TableCell>
                      <TableCell className="hidden sm:table-cell text-sm md:text-base lg:text-lg">
                        <Badge className="text-xs md:text-sm lg:text-base" variant="outline">
                          Upcoming
                        </Badge>
                      </TableCell>
                      <TableCell className="hidden sm:table-cell text-sm md:text-base lg:text-lg">2023-07-15</TableCell>
                      <TableCell className="text-right text-base md:text-lg lg:text-xl">$1,800.00</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>
                        <div className="font-medium text-base md:text-lg lg:text-xl">Fix bug in checkout</div>
                        <div className="hidden text-sm text-muted-foreground sm:inline md:text-base lg:text-lg">
                          Address a bug in the checkout process
                        </div>
                      </TableCell>
                      <TableCell className="hidden sm:table-cell text-sm md:text-base lg:text-lg">
                        <Badge className="text-xs md:text-sm lg:text-base" variant="secondary">
                          In Progress
                        </Badge>
                      </TableCell>
                      <TableCell className="hidden sm:table-cell text-sm md:text-base lg:text-lg">2023-06-25</TableCell>
                      <TableCell className="text-right text-base md:text-lg lg:text-xl">$750.00</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>
                        <div className="font-medium text-base md:text-lg lg:text-xl">Optimize database queries</div>
                        <div className="hidden text-sm text-muted-foreground sm:inline md:text-base lg:text-lg">
                          Improve database performance
                        </div>
                      </TableCell>
                      <TableCell className="hidden sm:table-cell text-sm md:text-base lg:text-lg">
                        <Badge className="text-xs md:text-sm lg:text-base" variant="outline">
                          Upcoming
                        </Badge>
                      </TableCell>
                      <TableCell className="hidden sm:table-cell text-sm md:text-base lg:text-lg">2023-07-01</TableCell>
                      <TableCell className="text-right text-base md:text-lg lg:text-xl">$1,200.00</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>
                        <div className="font-medium text-base md:text-lg lg:text-xl">Implement new analytics</div>
                        <div className="hidden text-sm text-muted-foreground sm:inline md:text-base lg:text-lg">
                          Add new analytics features
                        </div>
                      </TableCell>
                      <TableCell className="hidden sm:table-cell text-sm md:text-base lg:text-lg">
                        <Badge className="text-xs md:text-sm lg:text-base" variant="secondary">
                          In Progress
                        </Badge>
                      </TableCell>
                      <TableCell className="hidden sm:table-cell text-sm md:" />
                    </TableRow>
                  </TableBody>
                </Table>
              </CardContent>
            </Card>
          </div>
        </main>
      </div>
    </div>
  )
}

function CalendarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


function ClipboardIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="8" height="4" x="8" y="2" rx="1" ry="1" />
      <path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2" />
    </svg>
  )
}


function ClipboardListIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="8" height="4" x="8" y="2" rx="1" ry="1" />
      <path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2" />
      <path d="M12 11h4" />
      <path d="M12 16h4" />
      <path d="M8 11h.01" />
      <path d="M8 16h.01" />
    </svg>
  )
}


function DollarSignIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="2" y2="22" />
      <path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" />
    </svg>
  )
}


function LayoutGridIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="7" height="7" x="3" y="3" rx="1" />
      <rect width="7" height="7" x="14" y="3" rx="1" />
      <rect width="7" height="7" x="14" y="14" rx="1" />
      <rect width="7" height="7" x="3" y="14" rx="1" />
    </svg>
  )
}


function Package2Icon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9" />
      <path d="M12 3v6" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function SettingsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}


function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}
