"use client"
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/YDl3ydCPbc3
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Chivo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { TimerIcon } from "lucide-react"
import { ClockIcon } from "lucide-react"
import { ListIcon } from "lucide-react"
import { UserIcon } from "lucide-react"
import { SettingsIcon } from "lucide-react"

export default function Workplace() {
  const handleCreateAccount = async() => {
    const response = await fetch('http://localhost:3002/create-keypair',{
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
    });
    const data = await response.json();
    console.log(data);
  }
  return (
    <div className="flex min-h-screen w-full">
      <div className="flex flex-col w-[35vh] border-r bg-[#0B0014] text-white ">
        <div className="flex h-[60px] text-2xl items-center border-b px-6">
          <Link href="#" className="flex items-center gap-2 font-semibold" prefetch={false}>
            <TimerIcon className="h-6 w-6 text-[#26A7F7]" />
            <span className="">TaskChain</span>
          </Link>
        </div>
        <div className="flex-1 overflow-auto py-2">
          <nav className="grid gap-1 px-4 text-xl font-medium">
          <div className="flex items-center gap-2 text-muted-foreground">
              <Button onClick={handleCreateAccount} className="bg-[#022D50] px-2 py-2 w-[14vw] h-[5vh] text-md hover:bg-[#17507e] text-white">Add Wallet</Button>
            </div>
            <Link
              href="#"
              className="flex items-center gap-5 rounded-lg px-3 py-3 text-primary transition-all hover:bg-[#022D50]"
              prefetch={false}
            >
              <UserIcon className="h-4 w-4" />
              Account
            </Link>
            <Link
              href="#"
              className="flex items-center gap-3 rounded-lg px-3 py-3 text-muted-foreground transition-all hover:bg-[#022D50]"
              prefetch={false}
            >
              <SettingsIcon className="h-4 w-4" />
              Settings
            </Link>
            
            <Link
              href="#"
              className="flex items-center gap-3 rounded-lg px-3 py-3 text-muted-foreground transition-all hover:bg-[#022D50]"
              prefetch={false}
            >
              <ClockIcon className="h-4 w-4" />
              History
            </Link>
            <Link
              href="#"
              className="flex items-center gap-3 rounded-lg px-3 py-3 text-muted-foreground transition-all hover:bg-[#022D50]"
              prefetch={false}
            >
              <ListIcon className="h-4 w-4" />
              Manage Tasks
            </Link>
          </nav>
        </div>
      </div>

    <div className="container mx-auto py-12 px-4 md:px-6 lg:px-8">
      <div className=" md:grid-cols-2 gap-8">
        <div>
          <h1 className="text-3xl font-bold mb-4">Web Development Task</h1>
          <p className="text-muted-foreground mb-6">
            We're looking for an experienced web developer to help us build a modern, responsive website for our
            company. The scope of the project includes:
          </p>
          <ul className="space-y-2 text-muted-foreground">
            <li>
              <strong>Scope:</strong> Design and develop a fully-functional website with 5-10 pages, including a home
              page, about page, services page, and contact page.
            </li>
            <li>
              <strong>Requirements:</strong> The website should be built with React, utilize a component library like
              Tailwind UI, and be optimized for performance and accessibility.
            </li>
            <li>
              <strong>Deliverables:</strong> A fully-functional website deployed to a hosting platform, along with the
              source code and any necessary documentation.
            </li>
          </ul>
        </div>
        <div className="mt-[5vw]">
          <h2 className="text-2xl font-bold mb-4">Upload Your Work Samples</h2>
          <p className="text-muted-foreground mb-6">
            Please provide links to your portfolio or upload relevant files to showcase your web development skills.
          </p>
          <div className="grid gap-4">
            <div className=" w-[20vw] ">
              <Input type="text" placeholder="Enter a link to your portfolio " className="flex-1 border-blue-400" />
             
            </div>
            <div>
              <Input type="file" className="w-[20vw] border-blue-400" multiple />
            </div>
            <Link
              href="/userdash"
             
            >
            <Button className="w-[10vw] bg-[#2d8ddb] hover:bg-[#17507e] text-white">Submit</Button>
            </Link>
          </div>
        </div>
        
      </div>
      
    </div>
    </div>
  )
}
